language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: Qf/zWfWl5huWW7fVRRxbQTHI9a5sakWgucUXPfbVNlS1RTjcMg1URh0kLLsMn0XH5VevMlz/ZWguhbe2NG5FX65knmm5Aryjk9bnvD0oTCU8+NWlBfSAN0ff3mXIFmH99i1I+l+LgboVThtLRjftqiI94J0JAd0fTCYhns1UaI00J+dMC/9P+Shqx3D26s/9ygPvYDd4q237/LQYxNKGSlgNLq5vbpjKSrVteNl0moRKsP5u8ltaCvip/rzSqDJGRDNPC6fEkCJZBmUCKwwVEI36ZquOpAJKCeq1UXaSIGLm5jg/FZDqzUOcSLIqiSFL9kmo/C4A/unogLXNV2b6RdaMlj6FKKmIN4ZGRA+wRoalc+vrA07RzlzRQyMSXqFQKGpZ6GJo6TuR+T8NgihuErscgMiwB6g/F7rkN5oFAbLqHEJMuFC2N8MYia5bvr1oHUsZCxc8ePI49guqVqvNqak2otYGa8YEQALcDCbe8dPecWEa8RhRXNrTOteCGGtxuOl6XN2NUZMxezLHAeFhcw2I5as5SbuMudqZOF+ckBTP8m38nUsQtqS4k+vMZgP4C450rdZ7FTBhW4WpIvV7KTQ+aKdNASz3nWa4UMdjWoUCtEEW2NLGG6ydxeJVqBkbGCS15vHGxyMkyz0neQO4/mx+IvBf+/GbPYEQG+83X0A=
  app: dominikc-jalgoarena-problems
  on:
    repo: dominikc2/JAlgoArena-Problems
